# 项目名称，必填字端
name: study_flutter
# 项目描述，非必填
# 若需要将项目托管在pub.dev则该字段必填。
description: Flutter Study

# 是否将项目发布到 pub.dev
# none 表示私有项目
publish_to: 'none'

# 项目版本号，非必填
# 若需要将项目托管在pub.dev则该字段必填。
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# 项目的第三方插件依赖，在这个标签中列出了该项目正常工作所需的每一个软件包与版本。
dependencies:

  # 指定Flutter SDK，并获取SDK最新版
  flutter:
    sdk: flutter

  # Flutter默认图标库
  cupertino_icons: ^1.0.4
  # 网络请求库
  dio: ^4.0.3
  # Toast
  fluttertoast: ^8.0.8
  # 存储库(并非所有系统都支持)
  path_provider: ^2.0.2
  # GetX 状态管理、路由管理、依赖管理
  get: ^4.6.1

# 开发环境依赖
dev_dependencies:
  flutter_test:
    sdk: flutter

# 项目中配置声明方式
# 用于在项目中添加资源、设置字体、配置插件参数等。
flutter:

  # 是否使用 material-design 风格
  # 可以让项目允许使用 Material Icons类中的图标
  uses-material-design: true

  # 添加资源
  assets:
    - images/ic_login_scan.png

